server:
  port: 8082
  session:
    timeout: 30
  context-path: /buy
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 2000

spring:

  application:
    name: microservice-buy-provider
  session:
    store-type: none
  cache:
      type: REDIS
  devtools:
      restart:
        enabled: false
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true

  mvc:
    dispatch-options-request: true
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/,classpath:/templates/


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buydb?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,slf4j
  freemarker:
    request-context-attribute: request
  view:
     prefix: classpath:/templates/
     suffix: .html
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    host: localhost
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 3000
    # Redis服务器连接密码（默认为空）
    password:
    # 缓存管理器的默认失效时间，单位秒
    expireTime: 86400
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 2000
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 200
      # 连接池中的最小空闲连接
      min-idle: 50
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      mode: LEGACYHTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/,classpath:/templates/
rocketmq:
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: vehicleProducerGroup
    #mq的nameserver地址
    namesrvAddr: 10.10.2.20:9876
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: vehicleProducer
    #消息最大长度
    maxMessageSize: 131072 # 1024*128
    #发送消息超时时间
    sendMsgTimeout: 10000
    #发送失败重试次数
    sendMsgRetryTimes: 3

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  config: classpath:config/logback-spring.xml

token:
  signature:
    key: bwtwxmetro

global:
  workerId: 1
  sysName: 企业采购平台
  uploadBasePath: D:/dist
  activityBaseJsPath: https://cdn.bootcss.com/jquery/1.11.0/jquery.min.js,http://api.msx.bwton.com/api_h5/assets/js/Hextech.js

msxcxApi:
  baseUri: https://cs.msx.bwton.com/test104/api_v3/openapi
  appId: 4b4794a3b9004f25d8a4510232fc47cf
  version: "0100"
  secret: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCe7kxTTEHqe00ooigjsSpv9tvYaeaow0RTOx1gTkth/ypV6/QkVh9SkmQhgcWqzHvvCodNEje1rHBg75wxI3rPOuWlyQyNJnpMXdwK4T3WZ63+bIvEiEAEUl2xN5eYwpQg0VXTADNzXQKVrnWMFO2uT6OARev2HA2bNcFvvIDehwIDAQAB

ApiFilter:
  isCheckSignature: false
  token:
    signatureKey: bwtdist
  ignoreURIs: /security/generateApiClient,/duibatest/duibaTest,/duibatest/duibaTest1,/duibatest/duibaTestSpring,/duibatest/duibaTestSpringH5,/api/duiba/springAutoLoginAndAddTimes,/api/duiba/springAutoLogin,/api/duiba/autologin,/api/duiba/VirtualCharge,/api/duiba/rulesVerify,/duibatest/duibaTestH5,/api/duiba/getActivityId,/api/duiba/getScheduleTime,/api/duiba/userVerify,/api/duiba/ridings,/api/duiba/isPeriod,/api/duiba/verifyUserActivityDetail,/api/duiba/isEnable,/ueditor/exec

activityRule:
  ridingTimes: 0

swagger2:
  open: true

activity:
   #活动平台调用我方接口时验签开关
   isCheckSignature: false
   #兑吧平台应用appKey,此应用为测试营销活动时使用
   appKey: 4Sh8dr6LxF3aU11cgn8mHcPgFGFA
   #兑吧平台应用appSecret,此应用测试营销活动时使用
   appSecret: 4WVwXQ4V9i7gaDvx2TBRKh44bufh
   #兑吧平台的分销商代码
   distributorInfoCode: 661802
   #给兑吧生成的appid
   appid: 8da2b0814a8844d4a798a7cda97a2292
   #兑吧调用虚拟充值接口时，给用户兑换的奖品数量 如1张1次卡或1张5次卡
   chargeCardAmount: 1
   #给用户添加抽奖次数类型 0-永久 1-每天
   validType: 0
   #兑吧给用户添加次数接口的地址
   addTimesRomoteIp: https://activity.m.duiba.com.cn
   #兑吧给用户添加次数接口
   addTimesUri: /activityVist/addTimes
   #兑吧免登录接口地址前缀
   autoLoginPreUrl: http://www.duiba.com.cn/autoLogin/autologin?
   #兑吧兑换记录页面的dbredirect
   duibaRecordUrl: http://www.duiba.com.cn/crecord/record
eureka:
  client:
    serviceUrl:
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      #defaultZone: http://10.10.2.20:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


multipart:   
  enabled: true  
  max-file-size: 50mb  
  max-request-size: 50mb  
template:
  filePath: D:/template/
  uploadPath: D:/license